---
namespace: keycloak

stack:
  defines: process-group
  metadata:
    name: Keycloak
    shortname: Keycloak
    description: |
      Keycloak is an open-source identity and access management (IAM) solution developed by Red Hat. It provides a unified platform for managing user authentication, authorization, and security across multiple applications and services.

      Keycloak supports a wide range of authentication protocols, including OpenID Connect, OAuth 2.0, and SAML 2.0. It also provides a customizable user interface for managing users and groups, as well as a range of security features such as two-factor authentication, password policies, and brute-force attack prevention.

      One of the key features of Keycloak is its ability to integrate with a wide range of applications and services, including web applications, mobile apps, and microservices. It provides a single sign-on (SSO) solution that allows users to authenticate once and access multiple services without having to provide credentials multiple times.

      Keycloak also provides a range of integration options, including REST APIs, Java APIs, and a JavaScript API. This makes it easy for developers to integrate Keycloak into their applications and services, and to customize the authentication and authorization flows to meet their specific requirements.

      ---

      Notes:

      Default login/password: admin/admin.

      If running on unsecure http port, you need to run specific action to disable https requirement.

      To do that, connect to your cluster and issue a monk action:

      ``` bash
      monk do keycloak/keycloak/disable-admin-https
      ```

      Specify parameters like that: `user=admin pass=admin`.
    website: https://www.keycloak.org/
    source: https://github.com/keycloak/keycloak
    publisher: monk.io
    tags: Identity and access management (IAM), open-source, authentication, authorization, security, user management, group management, customizable user interface, two-factor authentication, password policies, brute-force attack prevention, single sign-on (SSO), integration options, REST APIs, Java APIs, JavaScript API, authentication protocols, OpenID Connect, OAuth 2.0, SAML 2.0
    icon: https://www.keycloak.org/resources/images/keycloak_logo_200px.svg
  runnable-list:
    - keycloak/postgres
    - keycloak/keycloak
  variables:
    db_name:
      type: string
      value: keycloak
    db_user:
      type: string
      value: monk
    db_pass:
      type: string
      value: monk
    kc_user:
      type: string
      value: admin
    kc_pass:
      type: string
      value: admin
